name: UltimateItemEdit
main: com.minkang.ultimate.itemedit.Main
version: 1.0.2
api-version: "1.16"
author: Mingang Jeon
website: "https://example.com"
commands:
  아이템이름:
    description: "손에 든 아이템의 표시 이름을 설정/삭제합니다."
    usage: "/아이템이름 <이름...> | /아이템이름 삭제"
    permission: ultimate.itemedit.name
    aliases: [iname]
  아이템설명:
    description: "손에 든 아이템의 설명(lore)을 추가/삭제합니다."
    usage: "/아이템설명 추가 <문장...> | /아이템설명 삭제"
    permission: ultimate.itemedit.lore
    aliases: [ilore]
permissions:
  ultimate.itemedit.*:
    default: op
    children:
      ultimate.itemedit.name: true
      ultimate.itemedit.lore: true
  ultimate.itemedit.name:
    default: op
  ultimate.itemedit.lore:
    default: op
